apiVersion: v1
kind: Pod
metadata:
  name: "sample"
  namespace: default
  labels:
    app: "sample"
spec:
  containers:
  - name: sample
    image: "debian-slim:latest"
    ports:
    - containerPort: 80
  restartPolicy: Always
